### ISSUE TITLE
Use Object.create(null); to create frozen/sealed objects

### ISSUE THREAD

**Issue by graingert** [keithamus/object-freeze-seal-syntax#11]
That way messing with Object.prototype would not effect these new object literals

**Comment by keithamus** [comment]
Agreed. This is in the plan for future changes to this spec

**Comment by graingert** [comment]
@keithamus where is the plan?

**Comment by keithamus** [comment]
Sorry @graingert. Plan is in my head. I'll be making changes soon to this proposal, but for now I'd happily accept a PR to change the existing examples - like those two commits you have (except I'd prefer to see the paths inline rather than as functions)

**Comment by graingert** [comment]
@keithamus babel supports helper functions, and with tranform runtime they are moved into imports, that way the code is much smaller
