### ISSUE TITLE
* for freeze (snowflake)

### ISSUE THREAD

**Issue by MaxDonchenko** [keithamus/object-freeze-seal-syntax#15]
As for me, `*` character fits better for `freeze` operation

```jsx
const foo = {*
  a: {*
    b: {*
      c: {*
        d: {*
          e: [* "some string!" *]
        *}
      *}
    *}
  *}
*}
```

**Comment by scf4** [comment]
This is much better. I also think {** ... } should deep-freeze.

**Comment by SebastianSimon** [comment]
Given that `({*x(){}})` is valid syntax now (creates an object with a generator method called `x`), this may be non-trivial to parse.

**Comment by MaxDonchenko** [comment]
And frozen generator will make code reading a hell 😈

Agree, closing
