### ISSUE TITLE
How does this interact with the record/tuple proposal?

### ISSUE THREAD

**Issue by theScottyJam** [keithamus/object-freeze-seal-syntax#27]
I understand that freezing/sealing objects will still be a valuable feature to have, even if/when [the record/tuple proposal](https://github.com/tc39/proposal-record-tuple) comes through. However ...
* A number of use cases this proposal solves will also be solved by the record/tuple proposal - would the decreased usefulness of Object.freeze() and Object.seal() still create enough demand to add special syntax for it?
* The currently proposed freeze syntax is extremely similar to the currently proposed record syntax: `{# ... #}` vs `#{ ... }`

If record/tuples gets through, are there plans to still continue pushing this proposal? If so, how would it accommodate the issues described above?

**Comment by keithamus** [comment]
For my purposes I think records and tuples are more useful than this proposal. I think if that proposal progresses much further - especially with the currently proposed syntax - I'll abandon this proposal.
