### ISSUE TITLE
"Freezing an functions destructured options bag" example seems incorrect

### ISSUE THREAD

**Issue by msegado** [keithamus/object-freeze-seal-syntax#7]
As written, the new syntax example contains what look like implementation details (including the `_ref1` variable), and the desugared version uses `let` instead of `const`... I'm guessing these were just copy/paste/editing errors and that it was intended to be more like the following?
```js
function ajax({# url, headers, onSuccess #}) {
  url = new URL(url) // throws TypeError('cannot assign to const `url`')
  fetch(url, { headers }).then(onSuccess)
}
ajax({ url: 'http://example.com', onSuccess: console.log })
```
*...desugars to...*
```js
function ajax(_ref1) {
  const _ref2 = Object.seal({ url: undefined, headers: undefined, onSuccess: undefined }) // seal now, const later
  Object.assign(_ref2, _ref1)
  const url = _ref2.url
  const headers = _ref2.headers
  const onSuccess = _ref2.onSuccess

  url = new URL(url) // throws TypeError('cannot assign to const `url`')
  fetch(url, { headers }).then(onSuccess)
}
ajax({ url: 'http://example.com', onSuccess: console.log })
```

**Comment by keithamus** [comment]
Hey @msegado thanks for the issue.

You're absolutely right! This looks like a copy paste error. How would you like to submit a PR correcting this?

**Comment by msegado** [comment]
Sure, thanks for the chance to contribute... just opened a PR.
